### ISSUE TITLE
检测时一直卡住不动

### ISSUE THREAD

**Issue by Yuliang-Lee** [midwayjs/mwts#11]
![image](https://user-images.githubusercontent.com/6936358/143524103-a576fadb-4894-4e42-840c-bc4508a03280.png)

用 node v16 和 node v14 都试过，都会卡住
mwts@^1.2.2

**Comment by czy88840616** [comment]
没碰到过哎，给我个复现 case？

**Comment by Yuliang-Lee** [comment]
破案了，eslint 扫描的目录包含了 prisma 生成的 client 文件，就会卡住
